[package]
name = "SLDeviceRustWrapper"
version = "0.1.0"
edition = "2021"

[lib]
name = "sl_device_rust_wrapper"

[dependencies]
cxx = "1.0.111"
thiserror = "1.0.51"

[build-dependencies]
cxx-build = "1.0.111"
