[package]
name = "wrapper"
version = "0.1.0"
edition = "2021"

[lib]
name = "wrapper"

[dependencies]
cxx = "1.0.111"
serde = { version = "1.0.194", features = ["derive"] }
thiserror = "1.0.51"
specta = { workspace = true }

[build-dependencies]
cxx-build = "1.0.111"
