[package]
name = "frontend"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "frontend_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { path = "C:/dev/repos/tauri/core/tauri", features = [] , version = "2.0.0-beta" }
# specta = { workspace = true }
# tauri-specta = { workspace = true }
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.7.0", features = ["serde"] }
wrapper = { path = "../../wrapper" }
chrono = { version = "0.4.34", features = ["serde"] }
once_cell = "1.19.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
